// <auto-generated />
namespace EventCalenderApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class foreign_key_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreign_key_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031602522_foreign_key_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
